export const LISTING_LIST_REQUEST = "LISTING_LIST_REQUEST";
export const LISTING_LIST_SUCCESS = "LISTING_LIST_SUCCESS";
export const LISTING_LIST_FAIL = "LISTING_LIST_FAIL";

export const LISTING_DETAIL_REQUEST = "LISTING_DETAIL_REQUEST";
export const LISTING_DETAIL_SUCCESS = "LISTING_DETAIL_SUCCESS";
export const LISTING_DETAIL_FAIL = "LISTING_DETAIL_FAIL";

export const MY_LISTINGS_REQUEST = "MY_LISTINGS_REQUEST";
export const MY_LISTINGS_SUCCESS = "MY_LISTINGS_SUCCESS";
export const MY_LISTINGS_FAIL = "MY_LISTINGS_FAIL";

export const NEW_LISTING_REQUEST = "NEW_LISTING_REQUEST";
export const NEW_LISTING_SUCCESS = "NEW_LISTING_SUCCESS";
export const NEW_LISTING_FAIL = "NEW_LISTING_FAIL";

export const UPDATE_LISTING_REQUEST = "UPDATE_LISTING_REQUEST";
export const UPDATE_LISTING_SUCCESS = "UPDATE_LISTING_SUCCESS";
export const UPDATE_LISTING_FAIL = "UPDATE_LISTING_FAIL";

export const DELETE_LISTING_REQUEST = "DELETE_LISTING_REQUEST";
export const DELETE_LISTING_SUCCESS = "DELETE_LISTING_SUCCESS";
export const DELETE_LISTING_FAIL = "DELETE_LISTING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
