export const CREATE_REQUEST_REQUEST = "CREATE_REQUEST_REQUEST";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_FAIL = "CREATE_REQUEST_FAIL";

export const SENT_REQUESTS_REQUEST = "SENT_REQUESTS_REQUEST";
export const SENT_REQUESTS_SUCCESS = "SENT_REQUESTS_SUCCESS";
export const SENT_REQUESTS_FAIL = "SENT_REQUESTS_FAIL";

export const RECEIVED_REQUESTS_REQUEST = "RECEIVED_REQUESTS_REQUEST";
export const RECEIVED_REQUESTS_SUCCESS = "RECEIVED_REQUESTS_SUCCESS";
export const RECEIVED_REQUESTS_FAIL = "RECEIVED_REQUESTS_FAIL";

export const UPDATE_REQUEST_REQUEST = "UPDATE_REQUEST_REQUEST";
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS";
export const UPDATE_REQUEST_FAIL = "UPDATE_REQUEST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
